<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>XenoSyncLauncher</RootNamespace>
		<AssemblyName>XenoSyncLauncher</AssemblyName>
		<ApplicationIcon></ApplicationIcon>
		<LangVersion>latest</LangVersion>
		<ApplicationIcon>Assets\icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Assets\img\logo.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2957.106" />
		<PackageReference Include="QRCoder" Version="1.6.0" />
		<PackageReference Include="QRCoder.Xaml" Version="1.6.0" />
		<PackageReference Include="SharpCompress" Version="0.37.2" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\img\logo.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>